language: generic

sudo: required
dist: trusty

services:
  - docker

env:
  - TESTID=vpn-1 OPT1=--env-file OPT2=./vpn.env.example
  - TESTID=vpn-2 OPT1= OPT2=

install:
  - docker build -t vpn .
  - docker run --name "$TESTID" $OPT1 $OPT2 --restart=always -p 500:500/udp -p 4500:4500/udp -v /lib/modules:/lib/modules:ro -d --privileged vpn

script:
  - sleep 15
  - docker ps | grep "$TESTID"
  - docker logs "$TESTID"
  - docker exec -it "$TESTID" netstat -anpu | grep pluto
  - docker exec -it "$TESTID" netstat -anpu | grep xl2tpd
  - docker restart "$TESTID"
  - sleep 15
  - docker ps | grep "$TESTID"
  - docker logs "$TESTID"
  - docker exec -it "$TESTID" netstat -anpu | grep pluto
  - docker exec -it "$TESTID" netstat -anpu | grep xl2tpd

notifications:
  email:
    - linsongui@gmail.com
