language: generic

sudo: required
dist: trusty

services:
  - docker

install:
  - docker build -t vpnserver .
  - docker run --name vpnserver --env-file ./vpn.env.example -p 500:500/udp -p 4500:4500/udp -v /lib/modules:/lib/modules:ro -d --privileged vpnserver

script:
  - sleep 20
  - docker ps | grep -q vpnserver
  - docker logs vpnserver
  - docker exec -it vpnserver ipsec status
  - docker restart vpnserver
  - sleep 20
  - docker ps | grep -q vpnserver
  - docker logs vpnserver
  - docker exec -it vpnserver ipsec status
