name: buildx latest

on:
  push:
    branches: [master]
    paths-ignore:
      - .github/workflows/buildx-latest-debian-updates.yml
      - .gitignore
      - .travis.yml
      - docker-compose.yml
      - LICENSE.md
      - README.md
      - README-zh.md
      - vpn.env.example
  repository_dispatch:
    types: [start-buildx-workflow]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # @v2.3.1
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@373dafb963e27afd52567f12584adb676f5fd647 # @v3.1.0
      - name: Docker Hub Login
        if: success()
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login --username hwdsl2 --password-stdin 2>&1
      - name: Docker Buildx (build and push)
        if: success()
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg VERSION=latest \
            -t hwdsl2/ipsec-vpn-server:latest \
            --push \
            .
      - name: Clear
        if: always()
        run: |
          shred -u "${HOME}/.docker/config.json"
          rm -f "${HOME}/.docker/config.json"
