name: buildx latest

on:
  push:
    branches: [master]
    paths-ignore:
      - .gitignore
      - .travis.yml
      - docker-compose.yml
      - LICENSE.md
      - README.md
      - README-zh.md
      - vpn.env.example
  watch:
    types: [started]

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Hub Login
        if: success()
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login --username hwdsl2 --password-stdin 2>&1
      - name: Docker Buildx (build and push)
        if: success()
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg VERSION=latest \
            -t hwdsl2/ipsec-vpn-server:latest \
            --push \
            .
      - name: Clear
        if: always()
        run: |
          shred -u "${HOME}/.docker/config.json"
          rm -f "${HOME}/.docker/config.json"
